/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectInquiryRouteImport } from './routes/project-inquiry'
import { Route as ProductConfiguratorRouteImport } from './routes/product-configurator'
import { Route as PirVsRockWoolRouteImport } from './routes/pir-vs-rock-wool'
import { Route as PartnerPortalRouteImport } from './routes/partner-portal'
import { Route as PanelThicknessCalculatorRouteImport } from './routes/panel-thickness-calculator'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InvestmentCalculatorRouteImport } from './routes/investment-calculator'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FactoryLayoutGeneratorRouteImport } from './routes/factory-layout-generator'
import { Route as DownloadCenterRouteImport } from './routes/download-center'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSandwichPanelsRouteImport } from './routes/solutions.sandwich-panels'
import { Route as SolutionsRawMaterialsRouteImport } from './routes/solutions.raw-materials'
import { Route as SolutionsProductionLinesRouteImport } from './routes/solutions.production-lines'
import { Route as SolutionsFactoryDevelopmentRouteImport } from './routes/solutions.factory-development'
import { Route as SolutionsEngineeringConsultancyRouteImport } from './routes/solutions.engineering-consultancy'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectInquiryRoute = ProjectInquiryRouteImport.update({
  id: '/project-inquiry',
  path: '/project-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductConfiguratorRoute = ProductConfiguratorRouteImport.update({
  id: '/product-configurator',
  path: '/product-configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const PirVsRockWoolRoute = PirVsRockWoolRouteImport.update({
  id: '/pir-vs-rock-wool',
  path: '/pir-vs-rock-wool',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPortalRoute = PartnerPortalRouteImport.update({
  id: '/partner-portal',
  path: '/partner-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelThicknessCalculatorRoute =
  PanelThicknessCalculatorRouteImport.update({
    id: '/panel-thickness-calculator',
    path: '/panel-thickness-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentCalculatorRoute = InvestmentCalculatorRouteImport.update({
  id: '/investment-calculator',
  path: '/investment-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryLayoutGeneratorRoute = FactoryLayoutGeneratorRouteImport.update({
  id: '/factory-layout-generator',
  path: '/factory-layout-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadCenterRoute = DownloadCenterRouteImport.update({
  id: '/download-center',
  path: '/download-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSandwichPanelsRoute = SolutionsSandwichPanelsRouteImport.update({
  id: '/solutions/sandwich-panels',
  path: '/solutions/sandwich-panels',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRawMaterialsRoute = SolutionsRawMaterialsRouteImport.update({
  id: '/solutions/raw-materials',
  path: '/solutions/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsProductionLinesRoute =
  SolutionsProductionLinesRouteImport.update({
    id: '/solutions/production-lines',
    path: '/solutions/production-lines',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsFactoryDevelopmentRoute =
  SolutionsFactoryDevelopmentRouteImport.update({
    id: '/solutions/factory-development',
    path: '/solutions/factory-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEngineeringConsultancyRoute =
  SolutionsEngineeringConsultancyRouteImport.update({
    id: '/solutions/engineering-consultancy',
    path: '/solutions/engineering-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/download-center': typeof DownloadCenterRoute
  '/factory-layout-generator': typeof FactoryLayoutGeneratorRoute
  '/industries': typeof IndustriesRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/knowledge': typeof KnowledgeRoute
  '/panel-thickness-calculator': typeof PanelThicknessCalculatorRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/pir-vs-rock-wool': typeof PirVsRockWoolRoute
  '/product-configurator': typeof ProductConfiguratorRoute
  '/project-inquiry': typeof ProjectInquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/engineering-consultancy': typeof SolutionsEngineeringConsultancyRoute
  '/solutions/factory-development': typeof SolutionsFactoryDevelopmentRoute
  '/solutions/production-lines': typeof SolutionsProductionLinesRoute
  '/solutions/raw-materials': typeof SolutionsRawMaterialsRoute
  '/solutions/sandwich-panels': typeof SolutionsSandwichPanelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/download-center': typeof DownloadCenterRoute
  '/factory-layout-generator': typeof FactoryLayoutGeneratorRoute
  '/industries': typeof IndustriesRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/knowledge': typeof KnowledgeRoute
  '/panel-thickness-calculator': typeof PanelThicknessCalculatorRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/pir-vs-rock-wool': typeof PirVsRockWoolRoute
  '/product-configurator': typeof ProductConfiguratorRoute
  '/project-inquiry': typeof ProjectInquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/engineering-consultancy': typeof SolutionsEngineeringConsultancyRoute
  '/solutions/factory-development': typeof SolutionsFactoryDevelopmentRoute
  '/solutions/production-lines': typeof SolutionsProductionLinesRoute
  '/solutions/raw-materials': typeof SolutionsRawMaterialsRoute
  '/solutions/sandwich-panels': typeof SolutionsSandwichPanelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/download-center': typeof DownloadCenterRoute
  '/factory-layout-generator': typeof FactoryLayoutGeneratorRoute
  '/industries': typeof IndustriesRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/knowledge': typeof KnowledgeRoute
  '/panel-thickness-calculator': typeof PanelThicknessCalculatorRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/pir-vs-rock-wool': typeof PirVsRockWoolRoute
  '/product-configurator': typeof ProductConfiguratorRoute
  '/project-inquiry': typeof ProjectInquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/engineering-consultancy': typeof SolutionsEngineeringConsultancyRoute
  '/solutions/factory-development': typeof SolutionsFactoryDevelopmentRoute
  '/solutions/production-lines': typeof SolutionsProductionLinesRoute
  '/solutions/raw-materials': typeof SolutionsRawMaterialsRoute
  '/solutions/sandwich-panels': typeof SolutionsSandwichPanelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/customer-portal'
    | '/download-center'
    | '/factory-layout-generator'
    | '/industries'
    | '/investment-calculator'
    | '/knowledge'
    | '/panel-thickness-calculator'
    | '/partner-portal'
    | '/pir-vs-rock-wool'
    | '/product-configurator'
    | '/project-inquiry'
    | '/sitemap.xml'
    | '/api/chat'
    | '/solutions/engineering-consultancy'
    | '/solutions/factory-development'
    | '/solutions/production-lines'
    | '/solutions/raw-materials'
    | '/solutions/sandwich-panels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/customer-portal'
    | '/download-center'
    | '/factory-layout-generator'
    | '/industries'
    | '/investment-calculator'
    | '/knowledge'
    | '/panel-thickness-calculator'
    | '/partner-portal'
    | '/pir-vs-rock-wool'
    | '/product-configurator'
    | '/project-inquiry'
    | '/sitemap.xml'
    | '/api/chat'
    | '/solutions/engineering-consultancy'
    | '/solutions/factory-development'
    | '/solutions/production-lines'
    | '/solutions/raw-materials'
    | '/solutions/sandwich-panels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/customer-portal'
    | '/download-center'
    | '/factory-layout-generator'
    | '/industries'
    | '/investment-calculator'
    | '/knowledge'
    | '/panel-thickness-calculator'
    | '/partner-portal'
    | '/pir-vs-rock-wool'
    | '/product-configurator'
    | '/project-inquiry'
    | '/sitemap.xml'
    | '/api/chat'
    | '/solutions/engineering-consultancy'
    | '/solutions/factory-development'
    | '/solutions/production-lines'
    | '/solutions/raw-materials'
    | '/solutions/sandwich-panels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CustomerPortalRoute: typeof CustomerPortalRoute
  DownloadCenterRoute: typeof DownloadCenterRoute
  FactoryLayoutGeneratorRoute: typeof FactoryLayoutGeneratorRoute
  IndustriesRoute: typeof IndustriesRoute
  InvestmentCalculatorRoute: typeof InvestmentCalculatorRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PanelThicknessCalculatorRoute: typeof PanelThicknessCalculatorRoute
  PartnerPortalRoute: typeof PartnerPortalRoute
  PirVsRockWoolRoute: typeof PirVsRockWoolRoute
  ProductConfiguratorRoute: typeof ProductConfiguratorRoute
  ProjectInquiryRoute: typeof ProjectInquiryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  SolutionsEngineeringConsultancyRoute: typeof SolutionsEngineeringConsultancyRoute
  SolutionsFactoryDevelopmentRoute: typeof SolutionsFactoryDevelopmentRoute
  SolutionsProductionLinesRoute: typeof SolutionsProductionLinesRoute
  SolutionsRawMaterialsRoute: typeof SolutionsRawMaterialsRoute
  SolutionsSandwichPanelsRoute: typeof SolutionsSandwichPanelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-inquiry': {
      id: '/project-inquiry'
      path: '/project-inquiry'
      fullPath: '/project-inquiry'
      preLoaderRoute: typeof ProjectInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-configurator': {
      id: '/product-configurator'
      path: '/product-configurator'
      fullPath: '/product-configurator'
      preLoaderRoute: typeof ProductConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pir-vs-rock-wool': {
      id: '/pir-vs-rock-wool'
      path: '/pir-vs-rock-wool'
      fullPath: '/pir-vs-rock-wool'
      preLoaderRoute: typeof PirVsRockWoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-portal': {
      id: '/partner-portal'
      path: '/partner-portal'
      fullPath: '/partner-portal'
      preLoaderRoute: typeof PartnerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-thickness-calculator': {
      id: '/panel-thickness-calculator'
      path: '/panel-thickness-calculator'
      fullPath: '/panel-thickness-calculator'
      preLoaderRoute: typeof PanelThicknessCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-calculator': {
      id: '/investment-calculator'
      path: '/investment-calculator'
      fullPath: '/investment-calculator'
      preLoaderRoute: typeof InvestmentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory-layout-generator': {
      id: '/factory-layout-generator'
      path: '/factory-layout-generator'
      fullPath: '/factory-layout-generator'
      preLoaderRoute: typeof FactoryLayoutGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-center': {
      id: '/download-center'
      path: '/download-center'
      fullPath: '/download-center'
      preLoaderRoute: typeof DownloadCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sandwich-panels': {
      id: '/solutions/sandwich-panels'
      path: '/solutions/sandwich-panels'
      fullPath: '/solutions/sandwich-panels'
      preLoaderRoute: typeof SolutionsSandwichPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/raw-materials': {
      id: '/solutions/raw-materials'
      path: '/solutions/raw-materials'
      fullPath: '/solutions/raw-materials'
      preLoaderRoute: typeof SolutionsRawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/production-lines': {
      id: '/solutions/production-lines'
      path: '/solutions/production-lines'
      fullPath: '/solutions/production-lines'
      preLoaderRoute: typeof SolutionsProductionLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/factory-development': {
      id: '/solutions/factory-development'
      path: '/solutions/factory-development'
      fullPath: '/solutions/factory-development'
      preLoaderRoute: typeof SolutionsFactoryDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/engineering-consultancy': {
      id: '/solutions/engineering-consultancy'
      path: '/solutions/engineering-consultancy'
      fullPath: '/solutions/engineering-consultancy'
      preLoaderRoute: typeof SolutionsEngineeringConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAssistantRoute: AiAssistantRoute,
  CustomerPortalRoute: CustomerPortalRoute,
  DownloadCenterRoute: DownloadCenterRoute,
  FactoryLayoutGeneratorRoute: FactoryLayoutGeneratorRoute,
  IndustriesRoute: IndustriesRoute,
  InvestmentCalculatorRoute: InvestmentCalculatorRoute,
  KnowledgeRoute: KnowledgeRoute,
  PanelThicknessCalculatorRoute: PanelThicknessCalculatorRoute,
  PartnerPortalRoute: PartnerPortalRoute,
  PirVsRockWoolRoute: PirVsRockWoolRoute,
  ProductConfiguratorRoute: ProductConfiguratorRoute,
  ProjectInquiryRoute: ProjectInquiryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  SolutionsEngineeringConsultancyRoute: SolutionsEngineeringConsultancyRoute,
  SolutionsFactoryDevelopmentRoute: SolutionsFactoryDevelopmentRoute,
  SolutionsProductionLinesRoute: SolutionsProductionLinesRoute,
  SolutionsRawMaterialsRoute: SolutionsRawMaterialsRoute,
  SolutionsSandwichPanelsRoute: SolutionsSandwichPanelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
